package Evaluacion;


import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.BorderLayout;
import Evaluacion.Ventana;
import Evaluacion.VentanaInterna;
import java.awt.Dimension;
import java.awt.image.BufferedImage;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author antonio
 */
public class VentanaInternaCamara extends VentanaInterna {

    /**
     * Creates new form VentanaInternaCamara
     */
    private Webcam camara = null;
    
    //private Ventana ventana = null;
   
    private VentanaInternaCamara(Ventana v) {
        super(v);
        initComponents();
        camara = Webcam.getDefault();
        Dimension resoluciones[] = camara.getViewSizes();
        Dimension maxRes = resoluciones[resoluciones.length-1];
        camara.setViewSize(maxRes);
        if (camara != null)
        {
            WebcamPanel areaVisual = new WebcamPanel(camara);
            //areaVisual.setFitArea(false);
            if (areaVisual!= null)
            {
                getContentPane().add(areaVisual, BorderLayout.CENTER);
                
                pack();
            }
        }
        
        //this.ventana = v;
    }
    
    public static VentanaInternaCamara getInstance(Ventana ventana)
    {
        VentanaInternaCamara v = new VentanaInternaCamara(ventana);
        return (v.camara !=null?v:null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CapturaBoton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        CapturaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Capturar.png"))); // NOI18N
        CapturaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapturaBotonActionPerformed(evt);
            }
        });
        jPanel1.add(CapturaBoton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        if(camara != null)
        {
            camara.close();
        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void CapturaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapturaBotonActionPerformed
        // TODO add your handling code here:
        BufferedImage img = camara.getImage();
        
        if(img != null)
        {
            VentanaInternaImagen vi = new VentanaInternaImagen(this.ventana);
            vi.getLienzo().setImage(img);
            ventana.getEscritorio().add(vi);
            vi.setTitle("Pantallazo WebCam");
            vi.setVisible(true);
        }
    }//GEN-LAST:event_CapturaBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CapturaBoton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
