/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Evaluacion;

import java.io.File;
import uk.co.caprica.vlcj.component.EmbeddedMediaPlayerComponent;
import uk.co.caprica.vlcj.player.MediaPlayer;
import uk.co.caprica.vlcj.player.MediaPlayerEventAdapter;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;

/**
 *
 * @author antonio
 */
public class VentanaInternaVLCPlayer extends VentanaInterna {

    private class VideoListener extends MediaPlayerEventAdapter
    {
        @Override
        public void playing(MediaPlayer mediaPlayer) {
            PlayBotonVLC.setEnabled(false);
            PauseBotonVLC.setEnabled(true);
            StopBotonVLC.setEnabled(true);
        }
        
        @Override
        public void paused(MediaPlayer mediaPlayer) {
            PlayBotonVLC.setEnabled(true);
            PauseBotonVLC.setEnabled(false);
        }
        
        @Override
        public void stopped(MediaPlayer mediaPlayer) {
            PlayBotonVLC.setEnabled(true);
            PauseBotonVLC.setEnabled(false);
            StopBotonVLC.setEnabled(false);
        }
        
        @Override
        public void finished(MediaPlayer mediaPlayer) {
            PlayBotonVLC.setEnabled(true);
            PauseBotonVLC.setEnabled(false);
            StopBotonVLC.setEnabled(false);
        }
    }

    /**
     * Creates new form VentanaInternaReproduccion
     */
    private EmbeddedMediaPlayer vlcplayer = null;
    private File fMedia;
    
    private VentanaInternaVLCPlayer (File f, Ventana ventana)
    {
        super(ventana);
        initComponents();
        fMedia = f;
        EmbeddedMediaPlayerComponent aVisual = new EmbeddedMediaPlayerComponent();
        vlcplayer = aVisual.getMediaPlayer();
        vlcplayer.addMediaPlayerEventListener(new VideoListener());
        
        getContentPane().add(aVisual,java.awt.BorderLayout.CENTER);
        pack();
    }
    
    public static VentanaInternaVLCPlayer getInstance(File f, Ventana ventana)
    {
        VentanaInternaVLCPlayer v = new VentanaInternaVLCPlayer(f, ventana);
        return (v.vlcplayer!=null?v:null);
    }
    
    public void play() 
    {
        if (vlcplayer != null)
        {
            if(vlcplayer.isPlayable())
            {
                //Si se estaba reproduciendo
                vlcplayer.play();
            } 
            else
            {
                vlcplayer.playMedia(fMedia.getAbsolutePath());
            }
        }
    }
    
    public void pause()
    {
        if (vlcplayer != null)
        {
            if (vlcplayer.isPlaying())
            {
                vlcplayer.pause();
            }
        }
    }
    
    public void stop()
    {
        if (vlcplayer != null)
        {
            vlcplayer.stop();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PlayBotonVLC = new javax.swing.JButton();
        PauseBotonVLC = new javax.swing.JButton();
        StopBotonVLC = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(720, 540));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        PlayBotonVLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Play.png"))); // NOI18N
        PlayBotonVLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayBotonVLCActionPerformed(evt);
            }
        });
        jPanel1.add(PlayBotonVLC);

        PauseBotonVLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Pausa.png"))); // NOI18N
        PauseBotonVLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseBotonVLCActionPerformed(evt);
            }
        });
        jPanel1.add(PauseBotonVLC);

        StopBotonVLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Stop.png"))); // NOI18N
        StopBotonVLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopBotonVLCActionPerformed(evt);
            }
        });
        jPanel1.add(StopBotonVLC);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        this.stop();
    }//GEN-LAST:event_formInternalFrameClosing

    private void StopBotonVLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopBotonVLCActionPerformed
        // TODO add your handling code here:
        this.stop();
    }//GEN-LAST:event_StopBotonVLCActionPerformed

    private void PauseBotonVLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseBotonVLCActionPerformed
        // TODO add your handling code here:
        this.pause();
    }//GEN-LAST:event_PauseBotonVLCActionPerformed

    private void PlayBotonVLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayBotonVLCActionPerformed
        // TODO add your handling code here:
        this.play();
    }//GEN-LAST:event_PlayBotonVLCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PauseBotonVLC;
    private javax.swing.JButton PlayBotonVLC;
    private javax.swing.JButton StopBotonVLC;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
