/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Evaluacion;

import java.awt.BorderLayout;
import java.awt.Color;
import sm.amr.IU.Lienzo2DImagen;


/**
 *
 * @author antonio
 */
public class VentanaInternaImagen extends VentanaInterna {

    /**
     * Creates new form VentanaInternaImagen
     */
    
    private Lienzo2DImagen lienzo;
    public VentanaInternaImagen(Ventana v) {
        super(v);
        initComponents();
        
        lienzo = new sm.amr.IU.Lienzo2DImagen();
        //Pasarle al lienzo los botones de los atributos
        lienzo.setpuntoBoton(super.ventana.getPuntoBoton());
        lienzo.setLineaBoton(super.ventana.getLineaBoton());
        lienzo.setRectanguloBoton(super.ventana.getRectanguloBoton());
        lienzo.setElipseBoton(super.ventana.getEllipseBoton());
        lienzo.setCurvaBoton(super.ventana.getCurvaBoton());
        lienzo.setTrazoLibreBoton(super.ventana.getTrazoLibreBoton());
        lienzo.setPersonalizadaBoton(super.ventana.getPersonalizadaBoton());
        
        lienzo.setRellenoBoton(super.ventana.getRellenoBoton());
        lienzo.setGradoTransparenciaSlider(super.ventana.getGradoTransparenciaSlider());
        lienzo.setSeleccionarBoton(super.ventana.getSeleccionarBoton());
        lienzo.setAlisadoBoton(super.ventana.getAlisadoBoton());
        lienzo.setPunteadaBoton(super.ventana.getPunteadoBoton());
        lienzo.setDegradadoCheckbox(super.ventana.getDegradadoCheckbox());
        lienzo.setPaletaTrazo(super.ventana.getPaletaTrazo());
        lienzo.setPaletaRelleno(super.ventana.getPaletaRelleno());
        lienzo.setPaletaFondo(super.ventana.getPaletaFondo());
        lienzo.setGrosorCombobox(super.ventana.getGrosorCombobox());
        lienzo.setPaletaFrente(super.ventana.getPaletaFrente());
        lienzo.setVerticalCheckbox(super.ventana.getVerticalCheckbox());
        lienzo.setHorizontalCheckbox(super.ventana.getHorizontallCheckbox());
        
        getContentPane().add(lienzo, BorderLayout.CENTER);
        pack();
    }
    
    public Lienzo2DImagen getLienzo()
    {
        return(lienzo);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        this.lienzo.setModificadoresVentana();
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
